from pygame import Vector2

# WINDOW
WINDOW_WIDTH = 512
WINDOW_HEIGHT = 768

# SPEEDOMETER
SPEED_CHANGE_TIMER = 4  # in seconds

# PLAYER
PLAYER_SIZE = 0.25
PLAYER_VELOCITY = 0.04  # of WINDOW_WIDTH

# ENEMY
ENEMY_START_SIZE = 0.05
ENEMY_MAX_SIZE = 0.25
ENEMY_START_VELOCITY = 0.005  # of WINDOW_HEIGHT
ENEMY_ACCELERATION = 1.2
ENEMY_INTERVAL = (100, 200)  # in milis
